name: go_sport_app
description: "Vietnamese sports group coordination app with attendance management and payment integration"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Architecture dependencies
  # Riverpod removed - using Cubit/Bloc only
  
  # New architecture dependencies
  flutter_bloc: ^8.1.3      # Cubit state management
  get_it: ^8.0.0             # Dependency injection
  injectable: ^2.3.2         # DI annotations
  auto_route: ^7.9.0         # Auto-generated routing
  dio: ^5.4.0               # HTTP client
  hive: ^2.2.3              # Local storage
  hive_flutter: ^1.1.0      # Hive Flutter integration
  firebase_messaging: ^16.0.0  # Push notifications - latest version
  firebase_core: ^4.1.0     # Firebase core - latest version
  qr_flutter: ^4.1.0        # QR code generation
  
  # Authentication and security
  flutter_secure_storage: ^9.0.0  # Secure token storage
  local_auth: ^2.3.0        # Biometric authentication
  
  # UI and utilities
  intl: ^0.19.0             # Internationalization
  freezed_annotation: ^2.4.1  # Code generation
  json_annotation: ^4.8.1   # JSON serialization
  image_picker: ^1.0.7      # Image picking from gallery/camera

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.2
  http: ^1.5.0
  intl_phone_field: ^3.2.0
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1  # GetIt code generation
  auto_route_generator: ^7.3.0  # AutoRoute code generation
  
  # Testing
  mockito: ^5.4.4
  
  # App icons and splash screen
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true # Enable internationalization

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/sports_icons/
    - assets/images/payment_methods/
    - assets/images/illustrations/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# App icons configuration
# Note: Configuration ready for PNG logo. SVG to PNG conversion needed for full functionality.
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  min_sdk_android: 23
  remove_alpha_ios: true
  # TODO: Add image_path when PNG logo is available
  # image_path: "assets/images/go_sport_logo.png"

# Splash screen configuration  
flutter_native_splash:
  color: "#2E7D32"
  # image: "assets/images/go_sport_logo.png"  # TODO: Convert SVG to PNG
  color_dark: "#1B5E20"
  android_12:
    color: "#2E7D32"
    color_dark: "#1B5E20"
