// Mocks generated by Mockito 5.4.5 from annotations
// in go_sport_app/test/features/auth/services/phone_auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:go_sport_app/features/auth/services/api_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> checkFirebaseStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkFirebaseStatus,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> authenticateWithFirebase({
    required String? idToken,
    String? name,
    List<String>? preferredSports,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticateWithFirebase,
          [],
          {
            #idToken: idToken,
            #name: name,
            #preferredSports: preferredSports,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getCurrentUser(String? laravelToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [laravelToken],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> logout(String? laravelToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #logout,
          [laravelToken],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> deleteFirebaseAccount(
          {required String? idToken}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFirebaseAccount,
          [],
          {#idToken: idToken},
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> healthCheck() => (super.noSuchMethod(
        Invocation.method(
          #healthCheck,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> authenticatedRequest({
    required String? method,
    required String? endpoint,
    required String? laravelToken,
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticatedRequest,
          [],
          {
            #method: method,
            #endpoint: endpoint,
            #laravelToken: laravelToken,
            #body: body,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> updateUserProfile({
    required String? laravelToken,
    String? name,
    List<String>? preferredSports,
    Map<String, dynamic>? preferences,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [],
          {
            #laravelToken: laravelToken,
            #name: name,
            #preferredSports: preferredSports,
            #preferences: preferences,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<bool> testConnection() => (super.noSuchMethod(
        Invocation.method(
          #testConnection,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>> sendVerificationCode(
          {required String? phone}) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendVerificationCode,
          [],
          {#phone: phone},
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> registerWithPhone({
    required String? phone,
    required String? verificationCode,
    required String? name,
    required String? password,
    List<String>? preferredSports,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerWithPhone,
          [],
          {
            #phone: phone,
            #verificationCode: verificationCode,
            #name: name,
            #password: password,
            #preferredSports: preferredSports,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> loginWithPhone({
    required String? phone,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithPhone,
          [],
          {
            #phone: phone,
            #password: password,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<bool> isFirebaseEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isFirebaseEnabled,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
